"""Update col name from todo.completed to todo.is_complete

Revision ID: 7fe7f49e3ed8
Revises: a893e08f32e3
Create Date: 2020-04-20 20:13:26.416134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe7f49e3ed8'
down_revision = 'a893e08f32e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'completed', new_column_name='is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'is_complete', new_column_name='completed')
    # ### end Alembic commands ###
