"""add table `List` as parent table of `Todo`

Revision ID: 8cdcb15ced6f
Revises: 0570fd826ed8
Create Date: 2020-04-20 09:47:21.617226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdcb15ced6f'
down_revision = '0570fd826ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # Creating Uncategorized List to enforce list_id cannot be null on the todo table
    op.execute("INSERT INTO lists VALUES ('1', 'Uncategorized', 'Contains all todo items not belonging to a list');")
    op.execute("UPDATE todo SET list_id = 1 WHERE list_id is null;")
    op.alter_column('todo', 'list_id', nullable=False)
    op.create_foreign_key('todo_lists_id_fkey', 'todo', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_lists_id_fkey', 'todo', type_='foreignkey')
    op.alter_column('todo', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('todo', 'list_id')
    op.drop_table('list')
    # ### end Alembic commands ###
